version: '3.2'
services:
  psql:
    restart: always
    image: postgres:10.1-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_NAME=${POSTGRES_NAME}
#  nginx:
#    restart: always
#    image: portinarus/nginx
#    depends_on:
#      - frontend
#    ports:
#      - 80:80
#      - 443:443
#      - 8443:8443
#    volumes:
#      - backend:/home/portinarus
#  frontend:
#    restart: always
#    image: portinarus/frontend
#    volumes:
#      - /home/victor/projects/portinarus/frontend:/frontend
#    command: /bin/sh -c "npm run start-dev"
#    ports:
#      - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: kibana
    ports:
      - 5601:5601
volumes:
#  backend:
  esdata1:
  dbdata:
#  frontend:
